# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Torrent name')),
                ('url', models.URLField(blank=True, max_length=2014, null=True, verbose_name='Torrent URL')),
                ('downloaded', models.BooleanField(default=False, verbose_name='Is downloaded')),
                ('tfile', models.FileField(upload_to='uploads/', verbose_name='Torrent file')),
            ],
        ),
    ]
