# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfile',
            name='tfile',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Torrent file'),
        ),
    ]
