# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tfile', '0002_auto_20160320_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 20, 19, 8, 33, 842968, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
