# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfile', '0003_auto_20160320_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfile',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Torrent URL'),
        ),
    ]
