# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import tfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfile', '0004_auto_20160320_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfile',
            name='files',
            field=models.TextField(blank=True, null=True, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='tfile',
            name='tfile',
            field=models.FileField(blank=True, upload_to=tfile.models.tfile_upload, verbose_name='Torrent file'),
        ),
    ]
