# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tfile', '0004_auto_20160320_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=1024, verbose_name='English name')),
                ('name_ru', models.CharField(blank=True, max_length=1024, verbose_name='Russian name')),
                ('year', models.IntegerField(blank=True, verbose_name='Year')),
                ('kp_id', models.IntegerField(blank=True, verbose_name='Kinopoisk id')),
                ('kp_parsed', models.BooleanField(default=False, verbose_name='Kinopoisk parsed')),
                ('torrents', models.ManyToManyField(to='tfile.TFile', verbose_name='Torrents')),
            ],
        ),
    ]
