# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kp_id',
            field=models.CharField(blank=True, max_length=2014, verbose_name='Kinopoisk id'),
        ),
    ]
