# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160320_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cached',
            field=models.TextField(blank=True, null=True, verbose_name='Kinopoisk cache'),
        ),
    ]
