# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_cached'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Dir')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_dir',
            field=models.ManyToManyField(to='movie.MovieDir', verbose_name='Dirs'),
        ),
    ]
