# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170331_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movie.Genre', verbose_name='Genres'),
        ),
    ]
